module.exports = [
  // Object.freeze({
  //   name: 'Super',
  //   slug: 'super',
  //   permissions: {
  //     entityGrid: true,
  //     entityCreate: true,
  //     entityRead: true,
  //     entityUpdate: true,
  //     entityDelete: true,
  //     taxonomyCreate: true,
  //     taxonomyRead: true,
  //     taxonomyUpdate: true,
  //     taxonomyDelete: true,
  //     fileCreate: true,
  //     fileRead: true,
  //     fileUpdate: true,
  //     fileDelete: true,
  //     admin: true,
  //     user: true,
  //     settings: true,
  //     tools: true,
  //     ecommerce: true,
  //   },
  // }),
  Object.freeze({
    name: 'Admin',
    slug: 'admin',
    permissions: {
      entityGrid: true,
      entityCreate: true,
      entityRead: true,
      entityUpdate: true,
      entityDelete: true,
      taxonomyCreate: true,
      taxonomyRead: true,
      taxonomyUpdate: true,
      taxonomyDelete: true,
      fileCreate: true,
      fileRead: true,
      fileUpdate: true,
      fileDelete: true,
      admin: true,
      user: true,
      settings: true,
      tools: true,
      ecommerce: true,
    },
  }),
  Object.freeze({
    name: 'Editor',
    slug: 'editor',
    permissions: {
      entityGrid: true,
      entityCreate: true,
      entityRead: true,
      entityUpdate: true,
      entityDelete: true,
      taxonomyCreate: true,
      taxonomyRead: true,
      taxonomyUpdate: true,
      taxonomyDelete: true,
      fileCreate: true,
      fileRead: true,
      fileUpdate: true,
      fileDelete: true,
      admin: false,
      user: false,
      settings: false,
      tools: false,
      ecommerce: false,
    },
  }),
  Object.freeze({
    name: 'Guest',
    slug: 'guest',
    permissions: {
      entityGrid: true,
      entityCreate: false,
      entityRead: true,
      entityUpdate: false,
      entityDelete: false,
      taxonomyCreate: false,
      taxonomyRead: true,
      taxonomyUpdate: false,
      taxonomyDelete: false,
      fileCreate: false,
      fileRead: true,
      fileUpdate: false,
      fileDelete: false,
      admin: false,
      user: false,
      settings: false,
      tools: false,
      ecommerce: false,
    },
  }),
];
